### ISSUE TITLE
The example in the document is no longer working

### ISSUE THREAD

**Issue by mssun** [rust-fuzz/afl.rs#115]
![image](https://user-images.githubusercontent.com/1270392/31312679-b2b37f0c-ab7e-11e7-86c0-03c08cac2b21.png)

I think it is caused by the out-dated rust in the Dockerfile.

**Comment by dhuseby** [comment]
I'm seeing the same issue.

**Comment by frewsxcv** [comment]
coincidentally, the past couple weekends, i've worked on rewriting afl.rs. i published a new version (0.2) yesterday. i just updated the docs (which are pretty bare at the moment):

* https://rust-fuzz.github.io/book/afl/setup.html
* https://rust-fuzz.github.io/book/afl/tutorial.html

it shouldn't require docker shenanigans anymore, but the workflow has changed and you'll need to use a new `cargo afl` tool. let me know if you run into any issues and let me know how it goes!

going to close this for now since this issue seems to apply to the old version of afl.rs. if all goes well, i'll publicize [the latest rewrite](https://github.com/rust-fuzz/afl.rs/pull/116) on the interwebs and tell people to try it out

**Comment by frewsxcv** [comment]
oh and here's a little screen recording i threw toegether https://asciinema.org/a/148359
