### ISSUE TITLE
PSA for MacOS users to fix installation error

### ISSUE THREAD

**Issue by rw** [rust-fuzz/afl.rs#148]
I'm not sure if this should go into a FAQ or troubleshooting guide, but I fixed an installation error on MacOS today by removing the `binutils` package from homebrew. It turns out that `binutils` is not well-supported, and its `ar` tool was failing to produce a correct archive, which in turn caused the `afl.rs` installation process to fail.

With that fixed, `afl.rs` works beautifully--thanks for your hard work!

**Comment by steakknife** [comment]
`brew unlink binutils; rm -rf ~/.local/share/afl.rs; cargo install afl`

Probably should hard-code the path to `ar` as `/usr/bin/ar` in the build on mac to avoid dependency leaks because uninstalling binutils isn't a scaleable option due to other projects and scripts depending on it. If there's a problem with the binutils formula, it needs to be reported to homebrew & GNU/sourceware.

**Comment by frewsxcv** [comment]
> Probably should hard-code the path to `ar` as `/usr/bin/ar` in the build on mac to avoid dependency leaks

Makes sense to me 👍 

Here's the code that needs to change if someone has some time:

https://github.com/rust-fuzz/afl.rs/blob/07d594bc31f235ef420c959fe11115d9ab22f8b5/build.rs#L46

https://doc.rust-lang.org/reference/conditional-compilation.html

**Comment by frewsxcv** [comment]
fixed in https://github.com/rust-fuzz/afl.rs/pull/171
